# Generated by Django 4.2.7 on 2023-12-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='horario',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
    ]
