# Generated by Django 4.2.7 on 2023-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_remove_turno_horario_turno_fecha_turno_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
