# Generated by Django 4.2.7 on 2023-12-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
